### ISSUE TITLE
Proposal: Infobanner display priorisation / conditional hiding

### ISSUE THREAD

**Issue by christianwolters** [moodleuulm/moodle-theme_boost_campus#100]
Hi Kathrin,

I am using the infobanner (both options) for the first time this week to alert users to a maintenance downtime
and I really like it! Nicely done! : D

I'd like to propse a new option for theme_boost_campus_infobanner settings,
to prioritise which banner is displayed if both are activated.

This could look like this:

A checkbox setting to activate this feature
A dropdown setting with the options:

1. Show both banners
1. Show perpetual, hide timed
1. Show timed, hide perpetual

Option 1 is the "do nothing" option, as this is the current behavior. One could argue, that this option would render the activation checkbox unnecessary but I like to encapsulate a feature by explicit activation.

Option 2 is the use case that provoked this proposal. For now, I like to use the perpetual banner on the dashboard as warning that can be dismissed, and use the timed banner to inform in every context activated 24h before maintenace. As soon as the timed banner is active, it is not necessary to show the perpetual anymore. <- in my specific use case

Option 3 - the reverse of option 2 - should be implemented as well.

I'd like to here your thoughts on this, and would contribute this feature if it fits into this plugin.
(Though I would not immediatley jump on this, so if anyone else like to pitch in -> fine by me ; ))

Cheers
Christian

**Comment by abias** [comment]
Hi @christianwolters ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

In Boost Union, there are already more settings for configuring the information banners which should cover most of the things which you have mentioned here. If there is anything else you would like to see, please do not hesitate to create a new issue on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues.

Cheers,
Alex
