### ISSUE TITLE
Proposal: Add CLI scripts for info banner handling

### ISSUE THREAD

**Issue by christianwolters** [moodleuulm/moodle-theme_boost_campus#101]
Hey bc-community,

as mentioned in #100, I am using the infobanner feature in context of maintenance downtimes.

Maybe some options / functions would be handy to have accessible via CLI, e.g.
* de/activation of each banner type
* and the reset: perpibresetvisibility

Cheers
Christian

**Comment by abias** [comment]
Hi @christianwolters ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

Against this background, this issue has been ported over to https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/55 and will be handled there for Boost Union.

Cheers,
Alex
