### ISSUE TITLE
Login Page Customizations

### ISSUE THREAD

**Issue by mifantrax** [moodleuulm/moodle-theme_boost_campus#103]
Dear Kathrin, Alexander and the rest of the ones involved in this great theme.
How possible would it be to add some enhancements to the login page?

1.  Change the location of custom text or additional information somewhere hierarchical higher on on the page. Any custom information seems to be overlooked when it is on the bottom of the page sometimes even hidden on smaller screens.
2. Have a separate block for Forgotten Password recovery link
3. Add ability to prioritize login option based on institution defaults, for e.g we use Google Login as the default, also ability to customize the button, like adding your own domain if google login is restricted
I would be willing to contribute to this development, i have contacted another developer about a custom development however since this is also Boost Campus related i thought about asking here.

![Screenshot (2)](https://user-images.githubusercontent.com/2910506/100554203-6326ca80-3293-11eb-97c7-197bebc21a89.png)

**Comment by abias** [comment]
Hi @mifantrax  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

I agree with your proposal to improve the element placements on the login page. There are some ideas floating around behind the scenes for Boost Union and there will be a feature proposal issue created soon on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues. Play stay tuned.

Cheers,
Alex
