### ISSUE TITLE
Permissions for Wiki

### ISSUE THREAD

**Issue by jaedth** [moodleuulm/moodle-theme_boost_campus#104]
Hello.

I have recently had Moodle 3.10 installed on my server. I use the boost campus theme. When I asked the installer about the problem I have with Permissions, he updated to the latest versions of everything, then through trying out Adaptable and Classic, found that the problem only occurs in Boost and Boost Campus.

The problem is that there is always this error message: "Exception - Call to a member function get() on null"

when clicking on 

- Locally assigned roles
- Permissions
- Check permissions 

in the Moodle wiki (but not OU Wiki). 

Regards,

James Thomas

**Comment by abias** [comment]
Hi @jaedth ,

thanks for raising this issue.

However, I was not able to reproduce it on a Moodle 3.10 installation with Boost Campus.
Additionally, you wrote that this problem happens for you with Boost Campus _and_ Boost. Thus, I would like to direct you to https://tracker.moodle.org and ask you to create an issue for Boost in Moodle core which is the basis for Boost Campus.

Cheers,
Alex
