### ISSUE TITLE
FR: Easy inheritance for adapting theme settings to child themes

### ISSUE THREAD

**Issue by danowar2k** [moodleuulm/moodle-theme_boost_campus#109]
We're locally using inheritance to prevent having to copy/paste the whole Boost Campus settings to our own child theme.
I'm gonna do an example pull request how we're doing this. If you approve of it, I will provide the whole PR for changing to that method.

**Comment by danowar2k** [comment]
#110 is an example of what I mean.

**Comment by abias** [comment]
I have added my feedback in #110.

Cheers,
Alex

**Comment by abias** [comment]
Closing based on the feedback in #110
