### ISSUE TITLE
Versions for Moodle 3.3 and (coming) 3.4 branches ?

### ISSUE THREAD

**Issue by germanvaleroelizondo** [moodleuulm/moodle-theme_boost_campus#11]
I like this plugin a lot.

Is there an estimate as to when there will be a version available for the current MOODLE 3.3  and the soon to be released MOODLE 3.4 branches in the Moodle plugins database?

This theme seems to work nicely in both branches, but I have not done an extensive testing.

According to the stats at https://moodle.org/plugins/stats.php?plugin=theme_boost_campus , most of the users of this theme actually have a Moodle 3.3 version :)
![versions](https://user-images.githubusercontent.com/2671923/32012319-0997b2d2-b97d-11e7-9f19-c59bfb53335b.png)

Having the Moodle plugins database with this branches marked as supported will make it very easy to install from the web UI.

Thanks for a very nice plugin.

**Comment by Kathrin84** [comment]
Hi germanvaleroelizondo,
thanks for your appreciation for our plugin. It's really nice to hear these words.
The development of this plugin threw us a little back in our usual update cycle. 
As you already said, this plugin seems to work smoothly on the not yet officially supported version.
I understand your wish, however, we don't want to add a supported version label for a version we weren't able to test yet with this plugin.
We plan to support the versions 3.3 and 3.4 until the end of this year, but I can't promise this as a fixed date. I hope this answer helps though.
Best, Kathrin

**Comment by germanvaleroelizondo** [comment]
Thanks Kathrin.
