### ISSUE TITLE
Migrate get_course_information_banners() to use mustache instead of html_writer

### ISSUE THREAD

**Issue by danowar2k** [moodleuulm/moodle-theme_boost_campus#119]
This method still uses html_writer, I'd like it to use templates. I'll provide a PR in the future....

**Comment by abias** [comment]
Hi @danowar2k ,

thank for highlighting this issue.
There are several places in Moodle core which still use html_writer as well, but a PR to change this to mustache templates will be warmly welcomed!

Cheers,
Alex

**Comment by abias** [comment]
Hi @danowar2k ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

If you look at Boost Union, you will see that the information banner feature has been ported over, but that the banners are built with a mustache template there now.

So, as the functionality is already there on Moodle 4.x, so there is nothing left to port over to Boost Union.

Cheers,
Alex
