### ISSUE TITLE
Login background on signup page

### ISSUE THREAD

**Issue by frumbert** [moodleuulm/moodle-theme_boost_campus#121]
Login and Signup are part of the same kind of process, so I modified the core_renderer.php so that it puts the custom login background page onto the signup page too

       // MODIFICATION START.
        // Only add classes for the login page.
        if ($this->page->bodyid == 'page-login-index' || $this->page->bodyid == 'page-login-signup') {
 
You may wish to consider this change in future releases.

**Comment by abias** [comment]
Hi @frumbert ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

I agree with your proposal to show the login page background on the signup page as well. 

Against this background, I just made a quick check on Moodle 4.x with Boost Union and was happy to see that there is the login background shown already just as you proposed t.

So, as the functionality is already thre on Moodle 4.x, so there is nothing left to port over to Boost Union.

Cheers,
Alex
