### ISSUE TITLE
Moodle 4 compatibility

### ISSUE THREAD

**Issue by yanus** [moodleuulm/moodle-theme_boost_campus#123]
Good morning, is support for Moodle version 4 planned and if so what is the time frame for a compatible version?

**Comment by Aldises** [comment]
I'm also interested by a Moodle 4.0 Version

**Comment by lucaboesch** [comment]
Hi @yanus and @Aldises 
The successor of theme Boost Campus will be [Boost Union](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union) and Boost Campus will neither obtain upgrade steps nor be ported to Moodle 4.0.
The update scripting and enquiry of the existing code would unfortunately have meant too much work.
So it has been decided by the maintainers to do a fresh start.

Best,
Luca
