### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by Shanmugavadivelu7** [moodleuulm/moodle-theme_boost_campus#124]
Hi, I am new to boost campus theme. Can you direct me how to use the theme for my moodle4.1 version. Thank you :)

**Comment by abias** [comment]
Hi @Shanmugavadivelu7 ,

please have a look at https://github.com/moodle-an-hochschulen/moodle-theme_boost_union / https://moodle.org/plugins/theme_boost_union which is the successor of Boost Campus for Moodle 4.

Cheers,
Alex

**Comment by Shanmugavadivelu7** [comment]
hi @abias Thanks for the reply.

I have moodle 4.1 installed and I would like to replicate the same theme of boost campus for version 3.9. This may be some very basic level question but I am new to moodle themes. I like the interface where the Dashboard,My courses tab are in the left-top of the campus version. While I used boost union the structure of the interface is different. 
 
Can you please give some input on this. Thank you once again :)
