### ISSUE TITLE
Regarding moodle 4+ version

### ISSUE THREAD

**Issue by Shanmugavadivelu7** [moodleuulm/moodle-theme_boost_campus#125]
hi @abias  Thanks for the reply.

I have moodle 4.1 installed and I would like to replicate the same theme of boost campus for version 3.9. This may be some very basic level question but I am new to moodle themes. I like the interface where the Dashboard,My courses tab are in the left-top of the campus version. While I used boost union the structure of the interface is different.

Can you please give some input on this. Thank you once again :)

**Comment by whuml** [comment]
@Shanmugavadivelu7 

Dear Shanmugavadivelu7 
As published on Moodle plugins directory: [Theme Boost Campus](https://moodle.org/plugins/theme_boost_campus) will not be upgraded, enhanced or modified for Moodle 4.x.

The successor of Boost Campus, Theme Boost Union, is not just a replica or copy of obsolete functionalities. 
Like Moodle 4.x you will find lots of improvements provided for a enhanced and optimised user experience within Boost Union.
Major functionalities, like Menues, Dashboard, Blocks etc. can be adapted to your individual needs - and even more.
Feel invited to have a closer look at our "Theme Boost Union":
https://github.com/moodle-an-hochschulen/moodle-theme_boost_union / https://moodle.org/plugins/theme_boost_union 

Thank you on behalf of Boost Union Team!
Wolfgang
