### ISSUE TITLE
Setting "theme_boost_campus | showsettingsincourse" does not work for front page

### ISSUE THREAD

**Issue by Nullmann** [moodleuulm/moodle-theme_boost_campus#13]
When the setting above is checked, "unfolding" the settings via the gear wheel does work for courses, but not for the site home/front page (accessible with the url moodle.com/?redirect=0).

Installed moodle version is 3.3, OS is windows (windows installation package). This error could be reproduced on two different machines.

**Comment by Kathrin84** [comment]
Hi Nullmann,
thanks for reporting this issue. I wrote a patch for this:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/4e1bf9cec610809e8657b765b11f68616620f6c4

**Comment by Nullmann** [comment]
Yep, now the front page settings are being displayed the normal way (as if the checkbox wasnt checked for normal courses).
