### ISSUE TITLE
Changing role is not accessible if "incoursesettingsswitchtorole" and "showsettingsincourse" is not set.

### ISSUE THREAD

**Issue by Nullmann** [moodleuulm/moodle-theme_boost_campus#14]
When settings are as shown in the following screenshot, then the change role function is nowhere to be found:
![screenshot](https://user-images.githubusercontent.com/15816473/34880837-f9220448-f7b1-11e7-95e8-047de04a24fd.jpg)
(All of the above checkboxes are unchecked)

If the first setting is also checked, it is visible in to "fold open" menu.

**Comment by Kathrin84** [comment]
Hi Nullmann,

thanks for this issue. 
I wrote a patch for this bug:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/f6d1a761df0fafcaab5624f2595e99178698c05e

Best, Kathrin

**Comment by Nullmann** [comment]
It now works as intented. Maybe you could make it more user-friendly by disabling the second checkbox if the first checkbox is not checked?

**Comment by Kathrin84** [comment]
I would love to do this, but this is simply not possible yet. We already invested a lot of money to get such a functionality to hide settings dependent on other settings into the core.
Currently, the only solution is still to describe the dependency within the descriptive text...

**Comment by abias** [comment]
Hi Benedikt,

the tracker issue for the functionality which Kathrin mentioned is https://tracker.moodle.org/browse/MDL-52167. It is currently awaiting peer review and will hopefully be part of Moodle core soon. As soon as it's in Moodle core, we will revise our plugins to leverage the new functionality to clean up their settings pages.

Thanks,
Alex
