### ISSUE TITLE
Feature: dark navbar color selector

### ISSUE THREAD

**Issue by wimglasseesjibe** [moodleuulm/moodle-theme_boost_campus#15]
The dark navbar uses $gray-dark by default. I realize I can overrule this scss variable in the raw initial scss but it might be nice if we could set it with a color picker.

**Comment by Kathrin84** [comment]
Hi,
thanks for your request and your proposal.
We adapted this feature from the older themes delivered by Moodle core and orientated also on the Boostrap core behavior. There you can select just between a light and a dark version. 
If we would offer a color picker for that feature, any color could be picked which leads to problems with a lot of colors in combination with the link color.
So, as you already mentioned, you can change the color easily and individually in your Raw SCSS setting of theme_boost_campus.
Best, Kathrin

**Comment by wimglasseesjibe** [comment]
Hi Kathrin,

Fair enough. Although I guess the problem is always there. If you pick your brand color to be the same as $gray-dark you have that problem too, no?

Just for reference, to change $gray-dark I added this line to the Raw Initial SCSS

`$gray-dark : #170091 !default;`
