### ISSUE TITLE
site title with dark navbar uses brand color

### ISSUE THREAD

**Issue by wimglasseesjibe** [moodleuulm/moodle-theme_boost_campus#16]
shouldn't this be white like the rest of the navbar text/icons?

**Comment by Kathrin84** [comment]
Hi, 
thanks for your request. Could you precise this question a bit? On which page does this occur? Do you have a screenshot that shows the problem? 
Thanks and best, Kathrin

**Comment by wimglasseesjibe** [comment]
Hi Kathrin,

screenshot is at the bottom.

You'll notice that 'Oud-leerkrachten', the shortname for the site, is in brand color.

Hope this clarifies the issue.

Thanks,

Wim



![shortname](https://user-images.githubusercontent.com/15772483/35672878-2bbb4368-0740-11e8-82b1-1fdedec0e2ac.PNG)

**Comment by Kathrin84** [comment]
Hi Wim,
thanks for your answer. The design of the name is identical to Boost core: 
A box with the brand color around the site name:
![bildschirmfoto 2018-02-01 um 12 29 20](https://user-images.githubusercontent.com/4711883/35676348-b7cea916-074b-11e8-9e9c-3ab93cab23d7.png)
This is why I did not changed this as this does also work for the dark navbar.
If you already removed the box, you can also change the color and hover color individually in the raw SCSS setting.
I hope this helps.
Best, Kathrin

**Comment by wimglasseesjibe** [comment]
Hi Kathrin,

if I'm not mistaking, the 'boxed' version is only applied if you don't have
a logo. If you have a logo it shows the shortname in brand text color.

Cheers,

Wim

**Comment by Kathrin84** [comment]
Hi Wim,
thanks for the hint with the uploaded logo.
I improved this: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/be29ed79792df7b27a183589b60e525cc901cd33
The latest 3.3 version will be released in the Plugins repository soon.
I'll close this issue.
Best, Kathrin
