### ISSUE TITLE
default login page

### ISSUE THREAD

**Issue by aobeid** [moodleuulm/moodle-theme_boost_campus#19]
Please change: classes/output/corse_renderer.php" line 415 'core/login' to 'core/loginform'.
that caused filenotfound error.

**Comment by Kathrin84** [comment]
Hi aobeid,
have you seen that I released a new 3.4 version? 
I handled this template change there:
https://github.com/moodleuulm/moodle-theme_boost_campus/blob/fc47116ec6e3ad7068488eb7c46dcf4e48b34d50/classes/output/core_renderer.php#L435 (classes/output/course_renderer.php does not exist, but I think you mean this code line I linked).
Please install the latest release and give feedback if you still encounter problems.
Best, Kathrin
