### ISSUE TITLE
Moodle Theme boost campus issue

### ISSUE THREAD

**Issue by vipulfirodiya** [moodleuulm/moodle-theme_boost_campus#22]
I have installed boost campus plugin, but after installation, all href are replaced by #. So redirection to relevant pages is not taking place.
Please suggest solution. Thank You

**Comment by Kathrin84** [comment]
Hi vipulfirodiya,
could you provide more information regarding your instance, please?
Which Moodle version are you using, which version of boost_campus did you install?
What do you exactly mean with *all* href are replaced with #. So you cannot change, for example,  into a course or open your your profile page?
Best, Kathrin

**Comment by vipulfirodiya** [comment]
my moodle version is 3.4 and same for boost campus
After installing boost campus,
In Site Administration block, if i clicked on user button, it only changes
url to #linkusers but not redirecting to that page. This thing is happening
with all Anchor tags.

**Comment by Kathrin84** [comment]
Please see:
https://docs.moodle.org/34/en/Administration_block
```
The Boost theme in Moodle 3.2 onwards uses gear icon links to provide access to settings pages rather than the administration block.
```
So we don't provide support for this block and please have a try with theme_boost, I assume that it's not working there, too.

**Comment by vipulfirodiya** [comment]
But even if i click on User profile section in navigation bar, it doesn't
show drop-down list for dashboard, profile.....

**Comment by vipulfirodiya** [comment]
Is it also a version issue?

**Comment by Kathrin84** [comment]
Hi!
When using my theme, I don't have any problems with links, all menu are working as they intend to.
Did you verify that everything works with Boost core theme on your instance.
Can you provide a screenshot or some more information? It's really difficult for me to assume the cause with so few information...

**Comment by glowingsword** [comment]
> I have installed boost campus plugin, but after installation, all href are replaced by #. So redirection to relevant pages is not taking place.
> Please suggest solution. Thank You

Hi! Please, can you check, was the mbstring.func_overload looks like

`mbstring.func_overload = 2`

or with other another value, exept right value(0)? I have a same trouble, and the root of this problem was non-correct value of the mbstring.func_overload option in my php.ini...
