### ISSUE TITLE
Buttons in site administration dark with dark text

### ISSUE THREAD

**Issue by t-schroeder** [moodleuulm/moodle-theme_boost_campus#23]
I noticed that some buttons under Site administration look strange:

![unbenannt](https://user-images.githubusercontent.com/24255259/37094716-0bc4a6dc-2214-11e8-99bb-d93f1df9dafb.PNG)

To see them you need to go to Site administration > Courses > Manage courses and categories. You also need to have a bunch of courses for the buttons to show up. Here's a script that you can put in your Moodle root and run to create enough courses to reproduce this:

```php
<?php
define('CLI_SCRIPT', true);
require_once(dirname(__FILE__).'/config.php');
require_once($CFG->libdir.'/testing/generator/data_generator.php');

echo "Generating courses ...";
$gen = new testing_data_generator();
for ($i = 0; $i < 21; $i++) {
    $course = $gen->create_course();
    echo " $course->shortname";
}
echo "\n";
```

**Comment by Kathrin84** [comment]
Hi,
thanks for the report and the short script to reproduce.
By default it looks like this:
![course_management](https://user-images.githubusercontent.com/4711883/37905828-74078444-3100-11e8-9065-9d0fcaa0ea76.png)
This pink color is the default brand info color from Moodle core. You can change this in boost_campus with the setting: theme_boost_campus | brandinfocolor.
I assume that you changed it already to the above seen dark color.
So this is not a bug - you simply have to optimize your brand info color. :)
Best, Kathrin
