### ISSUE TITLE
thead in capability overview white on white background

### ISSUE THREAD

**Issue by t-schroeder** [moodleuulm/moodle-theme_boost_campus#24]
Go to Site administration > Users > Permissions > Capability overview. Select any capability. Then select _All_ roles. Click _Get the overview_. This is what it looks like:
![thead](https://user-images.githubusercontent.com/24255259/37904509-4f3cef0e-30fc-11e8-8a8d-cc89858b663f.gif)
As you can see, the links to the roles in the thead are white on a white background until you hover over them.

The cause for that seems to be:
```css
thead a {
    color: #fff;
}
```

**Comment by Kathrin84** [comment]
Hi,
thanks for the report.
However, I cannot reproduce this:
![capability](https://user-images.githubusercontent.com/4711883/37905159-401e8652-30fe-11e8-8147-7ae80922fc54.png)
Are you sure this is with plain boost_campus and not a change in your own (RAW) SCSS?
I did not change any CSS rule regarding this aspect. This is all plain Boost functionality - the links are displayed with the $brand-primary color.
Best, Kathrin

**Comment by t-schroeder** [comment]
Oops. Yes, you are right. This is configured in our custom SCSS.
Sorry to have bothered you with this.
