### ISSUE TITLE
Hamburger Menue

### ISSUE THREAD

**Issue by MrAlbers** [moodleuulm/moodle-theme_boost_campus#27]
The  Boost-Campus Theme offers a lot of things that we missed in Moodle 3.4 in the Boost theme.- thanks for your effort.

It is nice that the entry  "Dashboard" in the hamburgermenue can be moved to the top also in course-view.
I wished I could also move "site-home", "calendar" and "private files", to the top of that menue.

Also, I would like to to be able to collapse the "my couses" list in that menue or make it disappear altogether. When subscribed to many courses that list is not complete anyway and the entry "more" takes me to "site-home" instead of showing my complete list of courses.
We use the legacy course owerview block on the dashboard and are quite happy with that.

Cheers Bernd Albers 

<img width="169" alt="hamburger menue -dashboard" src="https://user-images.githubusercontent.com/33703851/38470070-28e71836-3b5e-11e8-8b16-80348200ecec.PNG">
<img width="949" alt="hamburger menue -courseview" src="https://user-images.githubusercontent.com/33703851/38470072-2d42e8b0-3b5e-11e8-912b-6712766d6bcd.png">

**Comment by Kathrin84** [comment]
Hi Bernd,
thanks for your request.

> Also, I would like to to be able to collapse the "my couses" list in that menue or make it disappear altogether.

Have you seen that we are providing a local plugin that's addressing exactly this issue:
https://moodle.org/plugins/local_boostnavigation
With this plugin you can even add own nodes to different regions in the menu.

Regarding you proposal to keep all nodes above the course home node, we'll have to think this through.

Best, Kathrin

**Comment by MrAlbers** [comment]
Hi Katrin,
thanks for creating and pointing to that plugin, I've just installed it in Moodle 3.4.2+ and it does exactly what I need.

Now all I need is:
"I wished I could also move "site-home", "calendar" and "private files", to the top of that menue."
To my mind that would be logical, because these entries are part of the main-navigation, and not of the course-navigation as it looks now.
And for our users it is more convenient, to have the menue-items in the same place no matter if they are on the dashboard, in a course or elsewhere in Moodle.

Thanks for considering this proposal.

Cheers Bernd
