### ISSUE TITLE
When trying to enrol as a guest into a course, there is an error

### ISSUE THREAD

**Issue by Nullmann** [moodleuulm/moodle-theme_boost_campus#28]
The following error pops up, when a guest tries to access the guest enrolment of a course under /enrol/index.php?id=COURSEID

![screenshot](https://user-images.githubusercontent.com/15816473/39237499-0088f2a8-487c-11e8-958c-ed1b615ea5db.jpg)

The problem ist that the `$pageflatnav`-Object in `locallib.php:theme_boost_campus_set_node_on_top` is not set for a guest, resulting in the error.

It may be a problem with your plugin [boostnavigation](https://github.com/moodleuulm/moodle-local_boostnavigation) which we have installed here at the TU Darmstadt, but we are not sure and this is just a thought.

I will create a pull-request fixing this issue.

**Comment by Kathrin84** [comment]
Hi Benedikt,
thank you for your bug report and the pointing to the right place. As I already commented in your pull request, I made a own patch for this: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/09ef123759ba1aec9fee1dd2626b29d6b8eab193.
Nevertheless it helped a lot to be able to fix this very quickly.
Thanks and best, Kathrin

**Comment by Nullmann** [comment]
Thank you for your fast reply and the correction of the provided code!
