### ISSUE TITLE
boost_campus seems not to work with moodle 3.5

### ISSUE THREAD

**Issue by rochelmeyer** [moodleuulm/moodle-theme_boost_campus#30]
Some elements of the page layout seem broken after switching to moodle 3.5
Going back to theme boost solves the issue, given that the beauty  of boost_campus is lost. Clearing caches does not help.

**Comment by Kathrin84** [comment]
Hi rochelmeyer,
thanks for your issue.
I know that and I'm already working on a Moodle 3.5 version. Please be patient for a short time until my work for the new version is finished.
Thanks and best, Kathrin

**Comment by Kathrin84** [comment]
I'm happy to announce that the new Moodle 3.5 version is published on the plugins repository:
https://moodle.org/plugins/theme_boost_campus
Please try Boost campus on Moodle 3.5 with the latest version. This should fix your broken displaying.
Please come back to me if it solved this issue for you.

**Comment by rochelmeyer** [comment]
WOW! Thanks!

**Comment by Kathrin84** [comment]
Okay, I assume this as a: Yes, it solved my problem. Therefore I'm closing this issue. Thanks again for your report.
