### ISSUE TITLE
Blocks can disappear if they are placed in the footer without the footer showing

### ISSUE THREAD

**Issue by Nullmann** [moodleuulm/moodle-theme_boost_campus#31]
When you enable the setting "No blocks in footer" in the boost campus settings:

<kbd><img src="https://user-images.githubusercontent.com/15816473/40413301-c4b601de-5e75-11e8-9dac-42f5e2f84299.jpg" /></kbd>

But still place Blocks in the Footer in their settings:

<kbd><img src="https://user-images.githubusercontent.com/15816473/40413346-e69dcc32-5e75-11e8-9d7e-f5bf8945f372.jpg" /></kbd>

They simply disappear and can not be accessed anymore without resetting the dashboard/block settings.

The same thing happens when you set "One block column in footer" and put the block into the middle or right footer-block.

Best regards,
Benedikt

**Comment by Kathrin84** [comment]
Hi Benedikt,
thank you for your issue.
Usually, blocks that were placed in a footer area that does not exist, for example by reducing the setting from 3 columns to 1 column, move to the default block region (side-pre) and I've tested this and verified the behavior again.
I've seen that you have more regions than the default Boost Campus theme. Maybe this could lead to the issue you are having with the blocks.

Nevertheless, I've improved the code to the amount that the regions that are not selected are no more shown in the region drop-down menu (https://github.com/moodleuulm/moodle-theme_boost_campus/commit/bc15971d8fe89d39c7d420f25ae4c8f0e7cfdcad) Hopefully this helps solving your issue. Please come back to me and let me know if it was helpful.

Best, Kathrin

**Comment by Kathrin84** [comment]
I assume that this issue is fixed for you and therefore I'll close this issue.
