### ISSUE TITLE
Loginform logo image is not responsive

### ISSUE THREAD

**Issue by AnsonArgyris** [moodleuulm/moodle-theme_boost_campus#32]
When loginform is set to true the logo above the form is not responsive.

![issue_screenshot](https://user-images.githubusercontent.com/13554586/42215103-bbb0ba3a-7ebd-11e8-96ba-33dd41af565f.png)

If this is not intended, it could be fixed with two additions to the img tag width="100%" height = "auto"  .

I'd open a pull request but it seems to be too much trouble for the simple fix :)

**Comment by Kathrin84** [comment]
Hi Erich,
thanks for your issue. As we don't use logos in our instance - we simply did not check this. Right now I'm on holidays. I'll try to address this next week, when I'm back at my desk.
Best, Kathrin

**Comment by AnsonArgyris** [comment]
Hi Kathrin,
thx for your response! Please enjoy your holidays! :)
Best, Erich

**Comment by Kathrin84** [comment]
Hi @AnsonArgyris,

finally I found time to deal with Boost Campus things / issues. Thank you for your code proposal. I added this to the SCSS file:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/3aa8259ab9ac40fff9197d702d04d4f3e429f4f7

This will be part of the next release v3.5-r2 coming in the nearer future.

I will close this issue as it is solved with this fix.

Best, Kathrin

**Comment by AnsonArgyris** [comment]
Hello @Kathrin84,

thank you for fixing the bug!

Best, Erich
