### ISSUE TITLE
overiding boost child core renderer

### ISSUE THREAD

**Issue by ilyasahsan123** [moodleuulm/moodle-theme_boost_campus#33]
hi

i am so confused about overiding core renderer from boost child. can you help me?

**Comment by Kathrin84** [comment]
Hi,
as this is not a theme_boost_campus related question, I'm sorry to say that I cannot provide any support here.
Please ask your question in the Moodle Forum - e.g. the "General developer forum": https://moodle.org/mod/forum/view.php?id=55
Best, Kathrin
