### ISSUE TITLE
theme_boost_campus_process_flatnav() raises error

### ISSUE THREAD

**Issue by hamishdewe** [moodleuulm/moodle-theme_boost_campus#35]
Each usage of get_user_preferences() in this function throws an error in 3.5. The second parameter should be the default value to return. Removing $USER from the parameters solves the issue.

**Comment by Kathrin84** [comment]
Hi @hamishdewe,

thank you very much for raising this issue. You're absolutely correct.
I've fixed it here:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/b26f098252ff55829a6476bd110ea8d55e685f2c

Best, Kathrin
