### ISSUE TITLE
Support for Moodle 3.6

### ISSUE THREAD

**Issue by gushagelberg2** [moodleuulm/moodle-theme_boost_campus#48]
Will you be updating you Boost Campus plugins for Moodle 3.6?
Thanks
Gus

**Comment by Kathrin84** [comment]
Hi @gushagelberg2,

yes we will be updating Boost Campus for Moodle 3.6 and it is even finished right now. The new release can be found in Moodle's plugin repository: https://moodle.org/plugins/pluginversion.php?id=18853.

As your question should be answered with this comment, I'll close this issue.

Best, Kathrin
