### ISSUE TITLE
Moodle 3.6 - Problems with messaging system

### ISSUE THREAD

**Issue by Kathrin84** [moodleuulm/moodle-theme_boost_campus#49]
Hi @rochelmeyer

A few weeks ago we made the decision to upgrade to the new version 3.6.1. and we have returned to the original theme of Moodle (Boost). Unfortunately, we found more problems, especially in the new message system among other details. The Moodle roadmap explains that for the next update they will make other significant changes. Predictably, we would experience new setbacks again.

I have translated a large part of your theme into Spanish, that has been my contribution. However, we have abandoned Boost Campus.

Greetings, Enrique

_Originally posted by @aguatacuperche in https://github.com/moodleuulm/moodle-theme_boost_campus/issues/46#issuecomment-451742386_

**Comment by Kathrin84** [comment]
Hi @rochelmeyer,

I split your comment into a new issue because this is not footer related anymore.

It is sad to hear that you abandoned Boost Campus. We give our best to keep this and our other plugins up to date. The theme needs a lot of attention because Core changes many things each major release. Currently I'm right in the middle of preparing this plugin for Moodle 3.6.

Concerning your issues. Could you describe the problems with the messaging system that are related with Boost Campus? It is a quite surprising issue for us as we did not change anything related to the messaging system in our theme.
So a detailed bug report would help us to get to the problem and help improving / fixing Boost Campus for 3.6.

Furthermore, the same question regarding your comment "amongst other things": If you encounter an issue, please open an issue here on GitHub with a detailed description of the problem and steps to reproduce. 

Thanks and best, Kathrin

**Comment by rochelmeyer** [comment]
To clean up the mess first: I am not the one who gave up boost_campus and returned to boost! Au contraire: I really like boost_campus and really have no intentions to switch to something differerent. 

The footer issue was the first problem i noticed, the issue with messaging came a few days later. Problem is, that the messaging window does not open at all and you can't even access messages via your profile page. So messaging is basically dysfunctional with 3.6.1 and boost_campus. Sadly, i found my programming skills to be insufficient to understand why it does not work or even think about a patch to fix hat. 

aguatacuperche was the one who found more issues than those described above.

**Comment by Kathrin84** [comment]
Hi @rochelmeyer,

sorry for that mistake! GitHub filled the "Hi phrase" by creating the issue from the comment itself and I haven't checked this.

Thank you very much for your response. I've got further questions:

`Problem is, that the messaging window does not open at all`
What messaging window do you mean exactly? The new sliding in window when clicking on the speech bubble icon in the navigation bar?

`and you can't even access messages via your profile page. `
What do you mean with this comment? Could you write some steps to reproduce and share some screenshots? Do you click on the link "Profile" in your user menu or do you click on "Messages" in your user menu?

With the current master branch of Boost Campus (btw the footer issue is fixed there) I cannot determine differences between the Moodle core from demo.moodle.net and my Moodle 3.6 with Boost Campus. Is it possible for you to check this, too?
I assume that some fixes I already made might have fixed this problem, too.

Best, Kathrin

**Comment by rochelmeyer** [comment]
Thanks for clarifying. I will send some screenshots later. 

I will also update our moodle to your latest commits and keep you updated about the problems we see (or don't see).

**Comment by Kathrin84** [comment]
Hi @rochelmeyer,

I've had the chance to see the bug myself. With a plain Boost Campus 3.5 version on a 3.6 Moodle the speech bubble icon is not clickable or the click does not do anything. If you go to the messages page nothing happens here. 
I can say that this behavior is fixed in the current master which I will release as the 3.6 version of Boost Campus.
If this is what you, amongst aguatacuperche, meant with this issue, I would like to close it as fixed.

If there are still some more bugs regarding this issue or you meant something completely different, please come back to me - so I would keep the issue open.

Best, Kathrin

**Comment by rochelmeyer** [comment]
Kathrin, the first image is boost_campus after klicking the messaging bubble (nothing happens). Second image shows default behaviour with theme boost. 
![screenshot moodle mitteilungen boost-campus](https://user-images.githubusercontent.com/14875217/52051964-621c9900-2555-11e9-918e-0a4b88625636.png)

This is what boost does: 
![screenshot moodle mitteilungen theme boost](https://user-images.githubusercontent.com/14875217/52051993-795b8680-2555-11e9-921a-53e930dab3ac.png)

**Comment by Kathrin84** [comment]
Thanks for the screenshots. That coincides with what I've written one comment above your latest comment. This issue is fixed in the 3.6 release of Boost Campus and therefore I will close this issue. Thank you very much for your input, very much appreciated!
Best, Kathrin

**Comment by rochelmeyer** [comment]
Thanks! Updated ... looks good.
