### ISSUE TITLE
Suppress i#back-to-top from print stylesheet

### ISSUE THREAD

**Issue by lucaboesch** [moodleuulm/moodle-theme_boost_campus#53]
Dear Kathrin and Alex
I've got a suggestion to make.
You could suppress the back-to-top fa-chevron-up from print stylesheet so it's vanished when printing out a page.
Best,
Luca

**Comment by Kathrin84** [comment]
Hi @lucaboesch,

thank you for raising this issue. It was a small fix and has landed in the plugin:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/86b250d50136f5454c6994630b8a50fdb0705872

It will be available in the next release in Moodle's plugins repository. :)

Best, Kathrin
