### ISSUE TITLE
3.7 Beta redirect error

### ISSUE THREAD

**Issue by aguatacuperche** [moodleuulm/moodle-theme_boost_campus#54]
Hello

Since the last 3 updates of version 3.7 (currently 20190511 in my test environment) an error has been detected in "redirect" giving a message 

"Fatal error: Class 'theme_boost\output\core\course_renderer' not found in /data/vhosts/nuryana.com/beta.nuryana.com/theme/boost_campus/classes/output/core/course_renderer.php on line 43"

when you try to enter a course. This does not happen in the other links (administration, for example) Considering that an update is expected this next May 20, maybe we should have planned a patch.

Greetings.

**Comment by Kathrin84** [comment]
Hi @aguatacuperche,

thank you very much for raising this issue.
The error message looks to me as if Boost has changed their renderer classes or the locations of the renderers. This should be fixable, but did not have a deeper look into it currently.

We know that Moodle 3.7 will be released on May 20th, but I cannot promise any date when I will find time to fix this as we're ourselves just updated to Moodle 3.6 in production and our work for the next release is yet to be planned...

Nevertheless we'll try our best!

Best, Kathrin

**Comment by ksteitz** [comment]
Hi Kathrin, 

this issue still exists with Moodle 3.7 stable. That results in a message without a possibilty to access a course, like aguatacuperche reported already: 
"Fatal error: Class 'theme_boost\output\core\course_renderer' not found in [mdl-webserver-path]/theme/boost_campus/classes/output/core/course_renderer.php on line 43"

At Dashboard the debugging in developer mode additionally says: 
line 732 of /user/lib.php: call to get_string()
line 916 of /user/lib.php: call to user_convert_text_to_menu_items()
line 3318 of /lib/outputrenderers.php: call to user_get_user_navigation_info()
line 219 of /lib/mustache/src/Mustache/Context.php: call to core_renderer->user_menu()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 134 of /localcache/mustache/1558513062/boost_campus/__Mustache_0e00354aa6f719bf3d0808b025ef704b.php: call to Mustache_Context->findDot()
line 36 of /var/www/html/localcache/mustache/1558513062/boost_campus/__Mustache_7a923f2aed48df668db088f8fd6ac434.php: call to __Mustache_0e00354aa6f719bf3d0808b025ef704b->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_7a923f2aed48df668db088f8fd6ac434->renderInternal()
line 191 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 139 of /theme/boost_campus/layout/columns2.php: call to renderer_base->render_from_template()
line 1370 of /lib/outputrenderers.php: call to include()
line 1300 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 121 of /admin/settings.php: call to core_renderer->header()

maybe the release notes will help (in upgrading notes https://docs.moodle.org/37/en/Upgrading#Possible_issues_that_may_affect_you_in_Moodle_3.7 i saw nothing helping)? 
https://docs.moodle.org/dev/Moodle_3.7_release_notes#Themes
or https://tracker.moodle.org/browse/MDL-62142 

Kind regards
Klaus

**Comment by Kathrin84** [comment]
Hi @ksteitz,

thank you for adding additional details to this bug report. We are aware of this major problem. 

Preparing (and fixing) Boost Campus for Moodle 3.7 has high priority for us. However, currently other internal issues have even higher priority. In fact, Moodle 3.7 is not scheduled for deployment here at our university before september.

Boost Campus is a community project. If you have ressources to identify and fix this issue, feel free to submit a pull request and to help to reduce the preparation time for the 3.7 version.

Best, Kathrin

**Comment by ppv1979** [comment]
Hi all, Boost theme's renderers were moved to core, so instead of 
`class course_renderer extends \theme_boost\output\core\course_renderer {`
on line 43  in **\theme\boost_campus\classes\output\core\course_renderer.php** 
should be 
`class course_renderer extends \core_course_renderer {`

**Comment by ksteitz** [comment]
Thanks a lot @ppv1979 that works fine! 
@Kathrin84 tested successfull and may be added to 3.7 branch! :-) 

> Hi all, Boost theme's renderers were moved to core, so instead of
> `class course_renderer extends \theme_boost\output\core\course_renderer {`
> on line 43 in **\theme\boost_campus\classes\output\core\course_renderer.php**
> should be
> `class course_renderer extends \core_course_renderer {`

**Comment by Kathrin84** [comment]
Thanks everyone for helping with this issue and also to @lucaboesch who directly provided a patch! 👍 There was one more place where the referencing had to be changed.

Here's the commit on the master branch: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/50bf2c7b485b43de4d18b25700a036e83c745ebc

Therefore I'll close this issue as fixed.

Best, Kathrin
