### ISSUE TITLE
Sections in nav drawer have borders

### ISSUE THREAD

**Issue by t-schroeder** [moodleuulm/moodle-theme_boost_campus#57]
Hello,

if you have a course using the Topics format and in that course's settings change the "Course layout" to "Show one section per page" you all of a sudden have borders between the sections in the nav drawer. These are not there when using the "Show all sections on one page".
![sections-all-on-one-page](https://user-images.githubusercontent.com/24255259/59618359-56a6c480-9128-11e9-9bae-ad1445a195bf.PNG)
![sections-one-per-page](https://user-images.githubusercontent.com/24255259/59618366-57d7f180-9128-11e9-8eaf-50d712614142.PNG)

**Comment by christianwolters** [comment]
Hey Tim,

interesting discovery, I haven't noticed that.

I don't know yet, if this is 
a) an inconsistency that should be fixed in this theme or
b) if this issue is a design choice that could/should be resolved via custom (s)css in your local deployment.

As I'm thinking about this, leaving aesthetics aside:
* borders have a clear advantage regarding usability as they clearly define the clickable/touchable area

Therefore I would like to discuss the "inversion of your PR": always show border in nav drawer.

What do you think about this?

Cheers,
Christian

**Comment by t-schroeder** [comment]
Hi Christian,

I agree that borders are good for showing where one element ends and the next begins. However, I also see the benefit in not having any borders between the sections and the section header here. It makes the sections appear as one block and separates them from the other elements in the nav-drawer. 

Ultimately I can't tell you what's best since a) I don't know that much about design/UX and b) we use a child theme of yours in which we override these rules anyway. So it's up to you how you want it to look.

The thing that was bugging me was just that changing this one specific setting causes the style of the section list to change. I'd be fine with either design as long as it's consistent.

Regards,
Tim

**Comment by Kathrin84** [comment]
Hi,

@t-schroeder, thank you very much for raising this issue and providing a pull request - both is very much appreciated. And thank you @christianwolters, too, for discussing this issue.

I just wanted to say that currently I'm busy to get all other plugins we maintain released for 3.7. After this, I think I'll have a chance to have a detailed look at this issue. Thanks for your patience.

Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @t-schroeder,

thank you very much for raising this issue, providing a patch and your patience. I've merged your pull request into the master and the changes will be available in the next version of the plugin in the Moodle plugins repository.

Your help is very much appreciated! 
I'll close this issue as fixed.

Best, Kathrin

**Comment by t-schroeder** [comment]
Hi Kathrin,

no worries. I'm happy to help.

This is an edge case anyway, if you ask me. Besides, I already fixed it in our child theme a while ago.

Regards,
Tim
