### ISSUE TITLE
Validating theme_boost_campus ... Error ... Required Moodle version [2019052000.05] 

### ISSUE THREAD

**Issue by edshih2016** [moodleuulm/moodle-theme_boost_campus#59]
Hello Tech Support,

Please your help ... 
I use Moodle 3.7 (Build: 20190520), and get an Error when installing the latest Boost Campus (v3.7-r2, 2019070500, released on 5 July 2019): 

Validating theme_boost_campus ... Error
[Error] Required Moodle version [2019052000.05] 
Installation aborted due to validation failure

How can I fix this error?  Thank you in advance.

**Comment by abias** [comment]
Hi @edshih2016,

you did ask this question on https://moodle.org/plugins/theme_boost_campus and did send personal messages on moodle.org with this question.
We are only doing voluntary support for this theme and are doing it here in Github. It not really nice to trigger support questions on multiple channels.

Having said that, the answer to your question is simple: 
With the latest version v3.7-r2 of Boost Campus, we made a change which is based on a recent weekly version of Moodle core. You have to update your Moodle core to be able to install this release of Boost Campus.

Please update Moodle core to at least weekly version 2019052000.05 or better to Moodle 3.7.1 (2019052001.00) which was just released this weekend.

Cheers,
Alex

**Comment by edshih2016** [comment]
Thank you so much, Alex! 
Sorry for causing the inconvenience to you all. 


Bests,
Edward


 




------------------ Original ------------------
