### ISSUE TITLE
In Boost Campus, activity navigation links become buttons

### ISSUE THREAD

**Issue by lucaboesch** [moodleuulm/moodle-theme_boost_campus#60]
Dear Boost Campus developers.

I noticed a thing I then did undo in our Boost Campus child theme.
The issue is that activity navigation items become buttons. But in Boost they are links.

I wonder if that is on purpose.

<img width="1122" alt="activitynav-boost_campus" src="https://user-images.githubusercontent.com/377279/60871050-4dde7580-a232-11e9-8b1a-87d1681e47a7.png">
<img width="1122" alt="activitynav-boost" src="https://user-images.githubusercontent.com/377279/60871051-4dde7580-a232-11e9-9956-03cd4d36a63c.png">

Best,
Luca

**Comment by Kathrin84** [comment]
Hi @lucaboesch,

thanks for raising this issue.

Yes, this is done by purpose: 
* https://github.com/moodleuulm/moodle-theme_boost_campus/blob/master/scss/post.scss#L507 (Commit: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/2b91be884716c0986e666963f9de9478acf0582f)
* https://github.com/moodleuulm/moodle-theme_boost_campus/blob/master/scss/post.scss#L558 (Commit: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/4dc0eca181a8eaf01a30d487aba8bf73b5c599d7)

We did this for better recognizability, affordance and distinguishability.
(Tracker issues https://tracker.moodle.org/browse/MDL-65972 | https://tracker.moodle.org/browse/MDL-65876 might be somehow related). We thought it would be good to have the activity / topic navigation designed differently from the specific activity internal navigation as they can occur close to each other.

I hope this answers your question. If you have any thoughts or comments, please let us know.

Just if you might wonder: Although we're eager to bring improvements into core, at that time, we were not able to this on top work, too. So it is only a feature of this theme.

Best, Kathrin

**Comment by lucaboesch** [comment]
Ah, great. Maybe there will sometimes be a solution in core which fits us all better.
There are too many buttons for my taste.
I'll close this issue here.
