### ISSUE TITLE
Improve Readme on individual block icons

### ISSUE THREAD

**Issue by christianwolters** [moodleuulm/moodle-theme_boost_campus#62]
Hi Kathrin, Hi Alex,
 
as I'm getting started with Boost Campus (finally!), I came across two small issues regarding your _description_ of block icons (not the functionality) in the readme and the resprective setting.

My use case: I don't want to enable block icons for all blocks, but rather define my own as raw SCSS.

**Font Awesome (FA) version**

- AFAIK Moodle still uses FA version 4, but the link in the description (http://fontawesome.io/icons/) refers to the newer FA version 5
- We should mention that version 5 icons do not work _or_ refer to the old icon list: https://fontawesome.com/v4.7.0/icons (and update this description as Moodle uses a newer FA version)

**CSS example not working anymore**

- this may need further investigation, but just providing the FA unicode in the content property is not working in my test-setting (Firefox 68 and Moodle 3.7)
- I had to add the FontAwesome font explicitly, e.g.:
`.block_people .card-block .card-title::before {font-family: "FontAwesome"; content: '\f0c0' ; }`
- It seems that this part needs more attention when moving to FA version 5 as you have to additionally specify the font-weight, see: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Cheers
Christian

PS: Most who edit their icons this way might figure this out anyway but: one might want to add the **non-breaking-space** character after the FA unicode to have a space between icon and block title. The unicode for nbsp is \00a0. With the example from above: `.block_people .card-block .card-title::before {font-family: "FontAwesome"; content: '\f0c0\00a0' ; }.`

**Comment by Kathrin84** [comment]
Hi @christianwolters,

thank you very much for this issue. As already spoken personally in Vienna, I'll address this as soon as my time allows it to deal with Boost Campus again.

Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @christianwolters,

finally I found time to address this issue. First of all thank you very much for your deep thoughts about this.
You're right. Moodle is still using Font Awesome in version 4. I've changed the link in the README.md file: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/e009b1c6f58290d68aa36b00c001d33b75d8c518

> his may need further investigation, but just providing the FA unicode in the content property is not working in my test-setting (Firefox 68 and Moodle 3.7)
> I had to add the FontAwesome font explicitly, e.g.:
> .block_people .card-block .card-title::before {font-family: "FontAwesome"; content: '\f0c0' ; }

I could not reproduce this aspect. If the setting "Block icon" is enabled, the font-family will be set by this stetting. So the code in the RAW SCSS just needs to override the content.
I don't know why you need to add the font-family again to get this working. Tested it with Moodle 3.7 and Firefox 70.0. Do you still face this problem?

> It seems that this part needs more attention when moving to FA version 5 as you have to additionally specify the font-weight, see: https://fontawesome.com/how-to-use/on-the-web/advanced/css-pseudo-elements

Thank you for this hint. We'll deal with it as soon as Moodle upgrades to Font Awesome version 5.

> PS: Most who edit their icons this way might figure this out anyway but: one might want to add the non-breaking-space character after the FA unicode to have a space between icon and block title. The unicode for nbsp is \00a0. With the example from above: .block_people .card-block .card-title::before {font-family: "FontAwesome"; content: '\f0c0\00a0' ; }.

Thanks for that hint, too. However, in my personal opinion, I would not recommend to add space character to gain space between elements. Just add a padding-right in your SCSS. 

Best, Kathrin

**Comment by christianwolters** [comment]
Hi Kathrin,

thank you for your feedback. I‘ll try the padding solution.

I‘m closing this issue now, as the main aspect of this ticket is covered.
Regarding the font-family property: I‘ll open another issue if it is still relevant.

Cheers
Christian
