### ISSUE TITLE
Coloured block in VideoJS player for audio files

### ISSUE THREAD

**Issue by monnardj** [moodleuulm/moodle-theme_boost_campus#63]
This theme changes the appearance of the big play button in the videojs player. This is ok for video files. However, when the media is an audio only file, it also adds a coloured rectangle underneath the controls :

<img width="411" alt="image" src="https://user-images.githubusercontent.com/5880250/64792519-d7375e80-d579-11e9-8918-faee887b3914.png">

Apparently, the existing CSS rule should take care of this 
`.video-js.vjs-audio .vjs-big-play-button {
    display: none;
}`

but it is superseded by two more specific rules :
`.video-js.vjs-paused .vjs-big-play-button, .vjs-paused.vjs-has-started.video-js .vjs-big-play-button {
    display: block;
}`

`.vjs-paused.vjs-has-started.video-js .vjs-big-play-button {
    display: block;
}`

If don't know if adding !important to the first rule is the right way to solve this ?

**Comment by Kathrin84** [comment]
Hi @monnardj,

thank you very much for raising this detailed issue. As soon as I can focus again on this plugin, I'll have a closer look at it to provide a patch.

Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @monnardj,

finally I found time to deal with this issue and provided a patch: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/e6e896c5a63ca9e278aecaacce8ea9830fe68dbd

In this patch we're also slimming down the video js skin in general.

This will be available with the next release of this plugin in the Moodle's plugins repo shortly.

I'll close this issue as fixed.

Best, Kathrin
