### ISSUE TITLE
Second image in login page background images never loads

### ISSUE THREAD

**Issue by wimglasseesjibe** [moodleuulm/moodle-theme_boost_campus#64]
It gives a white background instead.

**Comment by Kathrin84** [comment]
Hi @wimglasseesjibe,

thank you for raising this issue.

Could you please provide more information, that would make it possible for me to reproduce the error (also some steps to reproduce or the image you have problems with). We are using the theme on a 3.7.+ Moodle in our latest 3.7 Boost Campus version and we don't have any issues with that feature.

Does the web inspector show any error or are there any infos when debugging is turned on?

Best, Kathrin

**Comment by wimglasseesjibe** [comment]
I upgraded to 3.7.2+ last night (from 3.7.1+) and the problem seems to have disappeared. Go figure.

Sorry for the inconvenience,

Wim
