### ISSUE TITLE
Somehow the tour reset is lost. 

### ISSUE THREAD

**Issue by ofurlan** [moodleuulm/moodle-theme_boost_campus#65]
Somehow the tour reset is lost. theme_boost_campus | footerhideusertourslink is not checked but still do not appear. I move between themes and still not appear at the bottom of the screen

**Comment by Kathrin84** [comment]
Hi @ofurlan,

thank you very much for raising this issue. 
I've checked this with the latest version of Boost Campus (v3.7-r1) and a Moodle 3.7+ version and it works fine for me. So I cannot reproduce your problem.

Could you please provide some more detailed information that could help reproducing the bug?

You say:

>  I move between themes and still not appear at the bottom of the screen

This sounds to me like the link is not there in other themes, too. Or do I misunderstand your comment here?

Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @ofurlan,

do you have any news on this? Is this still an issue on your side?
Are you aware that the link does only appear on pages for which a user tour (with the current user role and theme) is displayed at all?

**Comment by ofurlan** [comment]
Thank you very much for your reply. I'm not having this issue anymore. Best
regards.

**Comment by Kathrin84** [comment]
Thank you very much for your reply. So I'll close this issue.
