### ISSUE TITLE
.single-section section header is indented

### ISSUE THREAD

**Issue by lucaboesch** [moodleuulm/moodle-theme_boost_campus#66]
With
```
.single-section {
        /* Align section title in single view left. */
        h3.sectionname {
            text-align: left;
            padding-left: 40px;
            padding-top: 1.5rem;
        }
```
You do left align the section header in the course formats when "Show one section per page" is chosen in "Course layout". That is great!
The title stands out though and does not really align on the left hand side.

Why is that? Is this arbitrary and on purpose?

<img width="690" alt="boost_campus_align_single_topics_section_header" src="https://user-images.githubusercontent.com/377279/69962143-a712b280-150d-11ea-8156-36909b8e356e.png">

If you enlighten me that would be great. I stand ready to do a pull request to fix this.

(I'd set padding-left to 1 rem instead of 40px. I'm on Moodle 3.6.7.)
 
Best,
Luca

**Comment by abias** [comment]
Thank you, @lucaboesch , for asking this reasonable question. 

I think this was not built by purpose in this way, perhaps Moodle core paddings have changed somehow and we did not notice it. We will check that.

**Comment by Kathrin84** [comment]
Hi @lucaboesch,
thank you very much for your issue and your patience. You know, the COVID-19 pandemic bounded all our ressources for other tasks. Now I found time to have a look at your comment.

The lines you mention have only affect if you are viewing the single topic. But there your are right, the 40px are not useful for the design, so I will remove this indent.

The screenshot you pasted shows core functionality:
![indent](https://user-images.githubusercontent.com/4711883/83637294-ad124a80-a5a7-11ea-9eb7-bfcd9391a5dd.png)

Best, Kathrin

**Comment by Kathrin84** [comment]
Hi @lucaboesch,

for the sake of completeness, here is the link to the patch:
https://github.com/moodleuulm/moodle-theme_boost_campus/commit/0d5790b959c53f5f2397ff9cd53df076f262d621

I hope this works well and does not break anything.
Nevertheless, I'll close this issue at this point. 

Best, Kathrin
