### ISSUE TITLE
Ability to push lang menu and custom menu to the right hand side

### ISSUE THREAD

**Issue by lucaboesch** [moodleuulm/moodle-theme_boost_campus#67]
I propose this as a feature request I could help to contribute.

In our theme we push the custom menu and the lang menu to the right hand side where the user profile and the messaging and notification icon resides.

<img width="1024" alt="custom menu and lang menu right" src="https://user-images.githubusercontent.com/377279/70334321-874cf880-1845-11ea-8561-5d3573276fe1.png">

That could be a configurable setting „custom menu and lang menu position“ with default „left“ but also „right“ as option to choose.

Count me in as feature owner for this, if that is wanted.

**Comment by abias** [comment]
Hi @lucaboesch  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

I am unsure if this proposal is still something which should be considered on Moodle 4.x as well as the custom menu and the language menu have undergone some changes there.

If you think there are still things to improve, please do not hesitate to create a new issue on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues.

Cheers,
Alex
