### ISSUE TITLE
Improve usability of course management page

### ISSUE THREAD

**Issue by stemiwe** [moodleuulm/moodle-theme_boost_campus#69]
We improved the usability of our course management page by 3 changes, I think it would be great to include them in boost_campus:

1. adding the search courses box to the top of the management view
2. showing both short name and full name for a course in the course area
3. adding a direct link to the selected course to the course view area

![managementview](https://user-images.githubusercontent.com/13886080/70710254-0e372080-1cdf-11ea-80d9-b466a2f039dd.png)

we accomplished this by changes in 
/course/management.php
/course/classes/management_renderer.php
/course/classes/management/helper.php
/course/classes/list_element.php

in /course/management.php add this line before "echo $renderer->management_form_start();" 

`echo $renderer->course_search_form($search);`

in /course/classes/management_renderer.php add a view button in the function search_listitem_actions:

```
       // View.
       $actions[] = $this->output->action_icon(
           new \moodle_url('/course/view.php', array('id' => $course->id)),
           new \pix_icon('i/course', \get_string('view')),
           null,
           array('class' => 'action-view')
       );
```

In /course/classes/management/helper.php add a view button in function get_course_listitem_actions:

```
       // View. 
           $actions[] = array(
           'url' => new \moodle_url('/course/view.php', array('id' => $course->id)),
           'icon' => new \pix_icon('i/course', \get_string('view')),
           'attributes' => array('class' => 'action-view')
       );
```

In /course/classes/list_element.php change function get_formatted_name:

`return format_string($this->__get('shortname'), true, $this->get_context()) . ' - ' . format_string($this->__get('fullname'), true, $this->get_context())`

**Comment by abias** [comment]
Hi @stemiwe ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

Against this background, I have ported your proposal over to https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/129. Please do not hesitate to add additional thoughts there and even submit a pull request to Boost Union.

Cheers,
Alex

**Comment by lucaboesch** [comment]
I think this change 'adding a direct link to the selected course to the course view area' would be great to include them in Moodle Core.
Please add an issue to https://tracker.moodle.org, @stemiwe.
The more thing are handled by Boost Union, the more templates etc have to be taken over and maintained over time.
Just my 2¢
