### ISSUE TITLE
add direct link to selecting default language to the language menu

### ISSUE THREAD

**Issue by stemiwe** [moodleuulm/moodle-theme_boost_campus#73]
many of our users were confused about the language menu, since it only temporarily switches languages, but does not hint at the existance of a "default language" setting in the profile.

this is why we included a link to the profile language settings at the bottom of the language menu:

![directlang](https://user-images.githubusercontent.com/13886080/70712409-0463ec00-1ce4-11ea-949a-f0ca31edcf56.png)

this change is very easy to do by changing the function render_custom_menu in core_renderer.php, adding two lines below ($haslangmenu):

```
$this->language->add('#');
$this->language->add(get_string('preferredlanguage'), new moodle_url('/user/language.php'), get_string('preferredlanguage'));
```

if you want to include this in boost_campus, i can make a pull request

**Comment by abias** [comment]
Hi @stemiwe  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

Against this background, I have ported your proposal over to https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/128. Please do not hesitate to add additional thoughts there and even submit a pull request to Boost Union.

Cheers,
Alex
