### ISSUE TITLE
enable hotkey <enter> to confirm

### ISSUE THREAD

**Issue by stemiwe** [moodleuulm/moodle-theme_boost_campus#74]
at our site, we have a unpublished change that enables hotkeys in moodle. we are planning to package it into a local plugin and releasing it, however, since boost_campus already catches some keys, it might be nice to include the most-often used functionalities into the theme:

- [enter] always presses the last primary button on the page (usually "save and display")

- when switching edit mode on or off, screen position is saved and restored (this only makes sense if the turn edit on/off button is always visible, i will make another issue for that change of ours)

- course settings dropdown menus are navigable by arrow keys, like other dropdowns: right now, almost all the dropdown menus in moodle are navigable with arrow-up and arrow-down or by pressing the first letter of a given item, the exception being the course settings dropdown menu. this can be changed by changing the moustache template for action_menu_settings_item, action_settings_link and action_menu_trigger.mustache - i'm attaching all 3 files to this issue

[action_settings_link.zip](https://github.com/moodleuulm/moodle-theme_boost_campus/files/3955740/action_settings_link.zip)

**Comment by abias** [comment]
Hi @stemiwe  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

In Boost Union, your second item is already solved. Your first and third item is still interesting, though.
If you think that these features should be integrated into Boost Union, then please do not hesitate to create an issue on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues.

Cheers,
Alex
