### ISSUE TITLE
V 3.8, 3.9 Support

### ISSUE THREAD

**Issue by mifantrax** [moodleuulm/moodle-theme_boost_campus#77]
Thanks a lot for the theme.
Just wanted to know what are the plans for 3.8 and 3.9 support. 
Danke!

**Comment by Kathrin84** [comment]
Hi @mifantrax,

thank you for this question. We're really happy to see that Boost Campus has many installations and we're really eager to maintain it the best way we can and  we try our best to update the theme as fast as we can to the latest version. However, as we are always updating our Moodle instance in April / October, our resources are very limited and from all our other (20+) plugins we maintain the theme always needs most work to do it's possible that the new release takes some time after a new Moodle version is being released.

Nevertheless, you can help us and test the current version (3.7-rx) on the latest Moodle version (3.8+) and create issues here, if you encounter any problems.
And if you would like to provide a patch, this would help us even more. :)

I hope this answer helps you and I will close this issue.

Best, Kathrin

**Comment by mifantrax** [comment]
Thank you for your reply Kathrin.
Yes i will gladly install the version you mentioned and report any bugs.
Thank you for your work!
