### ISSUE TITLE
Footer Blocks: Where are they?

### ISSUE THREAD

**Issue by sennewood** [moodleuulm/moodle-theme_boost_campus#8]
In **Footer Layout Settings** you can change the number of blocks in the footer. I changed the value to "Two blocks columns in footer", but I don't see where I have to go to edit the content of those two footer blocks.

**Comment by Kathrin84** [comment]
Hi Sebastian,
this setting provides the areas to be able to place blocks within the footer. I'll tell you how we do it:
I go to the website start page, turn editing on and create a new text block. Then I go to the settings of this block. There I enter a title and / or the content and at the bottom I can decide where the block  shall be placed. Here, you can then choose the footer block regions that you enabled with this feature:
![block_settings](https://user-images.githubusercontent.com/4711883/29702088-bf049be6-896f-11e7-819a-9a75ea33d596.png)
Other possibility is to create the block and then drag and drop it into the desired region within the footer.
I hope this helps!
Best, Kathrin
