### ISSUE TITLE
Scoll Up button Not Woking after latest Update

### ISSUE THREAD

**Issue by pkmkrishnakumar-zz** [moodleuulm/moodle-theme_boost_campus#81]
Hi

I have an Moodle Installation (Moodle 3.8.2 (Build: 20200309)) alonng with Boost Campus Theme Enabled.
Prior to 24th March , the Moodle being used with Boost Campus (v3.7-r4 (2020021200)). Everything seems to work seamlessly.
After updating to Boost Campus (v3.8-r1 (2020032400)), Scroll Up botton is not working in any page.

Thanks 

Krishnakumar Masimalai

**Comment by fa305757** [comment]
I have the same problem after update to Moodle 3.8.2+ (Build: 20200402). Scroll Up botton is not working in any page.
Thanks
Giovanni

**Comment by DHusband81** [comment]
I am using 3.8.2+ and experiencing the same problem with the scroll up button.

Thank you

**Comment by Kathrin84** [comment]
Hello all together,

thank you very much for your reports. We encountered the issue ourselves but unfortunately COVID-19 pandemic came across and bounded all of our resources for other tasks. Finally I can find some time to deal with Boost Campus issues.

I improved the back to top button to support accessibility better and with this improvement I unintendedly broke the click handler. 

I fixed it with this commit: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/67be21ac378053bfa248ec910bcd74c656f8f373

It will be available with the next 3.8 release of this plugin. If you don't want to wait for this you can also apply this patch on your Boost Campus if you need it urgently.

As this is fixed, I'll close this issue.

Thanks for your patience and sorry for breaking the button.

Best, Kathrin
