### ISSUE TITLE
Image area

### ISSUE THREAD

**Issue by DHusband81** [moodleuulm/moodle-theme_boost_campus#85]
Using 3.8.2+
There is an error on line 202 of locallib.php, with a bracket in the wrong place.
Also, the function theme_boost_campus_get_imageareacontent() does not return the image paths, so no images are displayed. If you have entered the alternate text, this is displayed.
Regards
David

**Comment by Kathrin84** [comment]
Hello @DHusband81,

thank you very much for raising this issue and for hinting to the wrong placement of one bracket. 👍 
In my tests the image was delivered correctly but in the case that only the link is not set but the alt text, I got some notices and errors.
So I invested a little bit further work and improved the code and extended the related Behat tests for this scenario: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/90b843bbbbb5bcb8e25a5e92d283383544c0d48c

In my tests (manually and with Behat) every case works fine now. 
The patch will be available in Moodle's plugins repository in the next days.

So I will close this issue as fixed.

Thanks again and best, Kathrin.
