### ISSUE TITLE
Turn Editing On Button Missing after Upgrade to Moodle 3.9

### ISSUE THREAD

**Issue by pkmkrishnakumar-zz** [moodleuulm/moodle-theme_boost_campus#87]
Hi

After upgrading to Moodle 3.9, Turn Editing On Button is missing.

![image](https://user-images.githubusercontent.com/29704829/84666871-46921280-af3f-11ea-8ef7-35c64e328cbd.png)

Kindly provide a work around to regain the icon.

Thanks

Krishnakumar Masimalai

**Comment by pkmkrishnakumar-zz** [comment]
Hi

I hope this is due to the change in  "MDL-67924 - Move turn editing on button out of the edit menu on boost"

Thanks

Krishnakumar Masimalai

**Comment by DHusband81** [comment]
I have the same issue.

David

**Comment by rochelmeyer** [comment]
Boost Campus is not yet ready for 3.9 - latest supported version is 3.8
It usually takes them a couple of weeks to catch up with moodle releases.

**Comment by esmoyer** [comment]
I thought I was crazy when I couldn't find the option! Was able to figure out I can turn the block editing on and that allows me to edit the courses for now.

**Comment by christianwolters** [comment]
Hi all, Hi @Kathrin84,

finally had time to look at this.

By re-enabling the edit button or rather moving it back to where it belongs,
the edit-button function in boost_campus is obsolete.

So for all of you, who want to get the button working again with Moodle 3.9, here is a **temporary hotfix:**

* open the file: boost_campus/classes/output/core_renderer.php
* and rename the function edit_button, e.g. into obsolete_edit_button

Moodle will then call the edit_button from the parent theme boost.

I'll go to through the code shortly, remove the feature (code, config, readme) and provide a PR.

Cheers
Christian

**Comment by Kathrin84** [comment]
Hi, @pkmkrishnakumar ,
thanks for raising this issue and yes, you're right. The HQ finally moved reimplemented the edit button into the course header. So our improvement is not necessary anymore and we can delete it from Boost Campus.

----

Hi @christianwolters,
thank you very much for providing a pull request for this issue.
After adding some small improvements to it, I merged it into the master branch: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/ff92f977d50320789fd265477a7cbdbda4fbfa9a

The patch will be available in the the next v3.9-r1 version of Boost Campus.

So, I'll close this issue as fixed.

Thanks again and best, Kathrin
