### ISSUE TITLE
Back to top Button doesn't work

### ISSUE THREAD

**Issue by ralfhilg** [moodleuulm/moodle-theme_boost_campus#88]
Within Moodle 3.8.3. we found that the back to top button/icon don't work (browser: Firefox). Clicking has no effect.

 Is this a known issue or is there a  workaround?

Ralf

**Comment by Kathrin84** [comment]
Hello @ralfhilg ,

for this issue, please see https://github.com/moodleuulm/moodle-theme_boost_campus/issues/81.

This is fixed and the fix will be part of the new release. As we're still working on a new feature that will be included there, the release will take couple more days.

If it's urgent, you can patch your Boost Campus v3.8.r1 with the fix.

Best, Kathrin

**Comment by Kathrin84** [comment]
In the meantime V3.8-r2 and v3.8-r3 have been released and therefore I'll close this issue as fixed.
