### ISSUE TITLE
Border rule next to all Labels

### ISSUE THREAD

**Issue by ppv1979** [moodleuulm/moodle-theme_boost_campus#92]
After "2020-08-07 - Added rule to show description border for all users for restricted activities" all resources "Label" in all courses receive this border. For activities the border is ok, but not for labels. Could it be fixed?

**Comment by Kathrin84** [comment]
Hello @ppv1979,

thank you very much for raising this issue. This is in fact a regression from the patch you mentioned. We were not aware that labels are added to the course with the same rule.

I fixed this: https://github.com/moodleuulm/moodle-theme_boost_campus/commit/76fa4c803b328d29a2c4f17dc1e670244026c83c

Now everything should be displayed correctly. If you encounter another regression (hopefully not :D ), please feel free to open up another issue.

This fix will be available in the next release in the Moodle plugins repository within the next days.

So, I'll close this issue as fixed.

Thanks again and best, Kathrin

**Comment by ppv1979** [comment]
@Kathrin84 I've just checked — everything seems to be ok, thanks.
