### ISSUE TITLE
Footer <520px

### ISSUE THREAD

**Issue by dennis2menace** [moodleuulm/moodle-theme_boost_campus#93]
If you don´t use a layout with different blocks, the Footer is not completely visible due to the CSS: 
.row-fluid {
   margin-right: -15px;
   margin-left: -15px;
}
I changed it in the advanced settings (raw scss) to 
.row-fluid {
   margin-right: 15px;
   margin-left: 15px;
}
CIAO Dennis

**Comment by Kathrin84** [comment]
Hello @dennis2menace ,

thank you for raising this issue.

I'm not sure if I understand your issue fully. Could you provide more explanation and / or a screenshot and could you please verify if the issue occurs only on Boost Campus or also on theme Boost? Which versions of Moodle and Boost Campus do you use?

Your proposed solution seems a little bit critical to me as you change a general CSS class that is applied in many places throughout Moodle.

Best, Kathrin

**Comment by dennis2menace** [comment]
The issue only appears on boost_campus. I use the latest version of boost_campus from this git (yesterday about midnight) and Boost delivered with Moodle 3.9.1. 
The footer is cutted off on the left site:
<img width="377" alt="Bildschirmfoto 2020-09-09 um 08 22 08" src="https://user-images.githubusercontent.com/70981920/92562287-01e3f200-f276-11ea-81e0-599e3ab61a50.png">

on the right site, there´s too much space, so you can swipe the mobile site to the right by accident:
<img width="376" alt="Bildschirmfoto 2020-09-09 um 08 23 21" src="https://user-images.githubusercontent.com/70981920/92562299-06a8a600-f276-11ea-89af-a9a026770b40.png">

It is only appearing on mobile devices <520px. On iPad it is fine:
<img width="438" alt="Bildschirmfoto 2020-09-09 um 08 24 06" src="https://user-images.githubusercontent.com/70981920/92562306-0a3c2d00-f276-11ea-8b17-77ccb9bcafba.png">

**Comment by Kathrin84** [comment]
Hi @dennis2menace ,

thanks for your further explanation and providing screenshots. 
Unfortunately I've got no physical device to test your scenario with. So I can only try to simulate this with the browser tools.

However, the simulation in the browser displays everything well with small resolution an not footer blocks enabled:
![simulated_small_res](https://user-images.githubusercontent.com/4711883/94662385-99ce7c00-0308-11eb-96ce-8126d9acd736.png)

Having a look at your navigation bar, I'm wondering that your burger menu item is not on the left side. So I assume you use a child theme of Boost Campus or added rules to the RAW SCSS section?

Can you reproduce the problem on a core Moodle 3.9 with a freshly installed Boost Campus, too?

Best, Kathrin

**Comment by abias** [comment]
Hi @dennis2menace ,

we surely would have liked to solve this problem.

However, as there wasn't any feedback anymore from you to @Kathrin84 's questions, I will close this now.
Please don't hesitate to come back again if you have more information for us.

Cheers,
Alex
