### ISSUE TITLE
H5P

### ISSUE THREAD

**Issue by dennis2menace** [moodleuulm/moodle-theme_boost_campus#94]
There ´s something missing:
If you navigate to H5P - /contentbank/index.php?contextid=1 you get the medias, you created. If you select one, there should be a **settings wheel** inside the card-body div. It is the only way to rename and especially to delete a h5p media. 
I think we will need this 😀

**Comment by Kathrin84** [comment]
Hi @dennis2menace,

thank you for raising this issue. Did you have a look at Issue #91 ? Does this describe what you reported here or is your issue an addition to #91?

Best, Kathrin

**Comment by dennis2menace** [comment]
Sorry for that! I had a short look over the other issues, but missed #91... ´was late yesterday :)

**Comment by Kathrin84** [comment]
Thanks for your response. Then I'll close this issue as duplicate.
