### ISSUE TITLE
Feature proposal - Global search

### ISSUE THREAD

**Issue by lane-interactive** [moodleuulm/moodle-theme_boost_campus#97]
Hello, thanks for the ongoing dev and support of this great theme. 

Just wondering if you could please consider modifying the functionality and persistence of the global search input field in top right bar area? 

I wish to hide the global search option in quiz entry pages and attempt pages. 

I also would like to make the global search results open in a new tab so students don't lose responses in textboxes if they search in a quiz (or anywhere in the site really). 

If there is a way for me to do this myself using SCSS please let me know?

**Comment by abias** [comment]
Hi @edcatalyst  ,

many thanks for creating this issue which remained unhandled up to now, unfortunately.

As we have documented on https://moodle.org/plugins/theme_boost_campus, Boost Campus will not be continued after Moodle 3.x anymore as we will focus on the successor Boost Union which is published on https://moodle.org/plugins/theme_boost_union. For the time being, as long as Moodle 3.x still receives security support, we will only fix critical bugs in Boost Campus if one arises. And, of course, we try to port over all relevant features of Boost Campus and open proposals for Boost Campus to Boost Union.

Against this background, if you think that there should be improvements for the global search on Boost Union as well, please do not hesitate to create a new issue on https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues.

Cheers,
Alex
