### ISSUE TITLE
Moodle 3.10 compatibility

### ISSUE THREAD

**Issue by yanus** [moodleuulm/moodle-theme_boost_campus#99]
I've upgraded to Moodle 3.10 today and the theme CSS seems to be broken, e.g.:
- the navbar icons (bell and speech bubble) are stacked on top instead of next to each other
- settings like 'brand color' and 'image area items maximal height' are ignored
- the custom SCSS is ignored

Tested on a clean installation of Moodle 3.10 with Boost Campus v3.9-r1 (see screenshot)
![Screenshot_2020-11-09 New Site](https://user-images.githubusercontent.com/5475686/98549220-c75cfc80-229a-11eb-9c3c-a2fdd88b6e06.png)

**Comment by aguatacuperche** [comment]
Hi,

The code "Raw initial SCSS" does not work either. "Login page background images" also fails.

v3.9-r2

**Comment by kobajashi77** [comment]
Same here in 3.10+ (2020110900) . 
I really appreciate all the work you but in the theme, the navigation extension and all the other plugins. Thank you very much for that! Cheers

**Comment by abias** [comment]
Hey @yanus @aguatacuperche @kobajashi77,

thank you all for raising these issues with 3.10.
You might want to look at the branch https://github.com/moodleuulm/moodle-theme_boost_campus/tree/LMS-5287 where I have push a WIP version of theme_boost_campus which contains fixes for all of these issues but which is not yet officially released for 3.10.

Cheers,
Alex

**Comment by aguatacuperche** [comment]
Hi @abias 

I have installed it and it has been resolved by clearing the cache. I have another experimental installation in a 4.0dev test version where it has been fixed as well.

Cheers

**Comment by yanus** [comment]
Dear @abias,

I can confirm that the new version seems to have solved all issues. Thank you for the great work on the theme!

Cheers,
Yannick

**Comment by kobajashi77** [comment]
Thanks @abias for your great work. Cheers Tobias

**Comment by abias** [comment]
The branch for the 3.10 version has now been merged into the master branch. An official release on moodle.org/plugin will follow soon.

Have fun!

Cheers,
Alex
